# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49bd80ba0f98e5f430ab7d7354ebac9fbdf18357b8bc565f645457158b55b17d337584e5c3ceeac404d263d44759cb9de2b720d66321cf6399f21a3fd34d59b6

test:
  secret_key_base: 19ba1d620ed90de3b78f9f8b6266823a9908fc0fda11c08ca438c9d840f0f25ac8f0de4d61fe3e316a63ac7ca0d18bc1bb495b5a09ed61a44e6eebe4fdef1988

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
